server:
  port: 8081
  ssl:
    key-store: C:\Users\Gabi\keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat
    key-password: password
#  port: 8443

  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
        password: gabriela
        url: jdbc:postgresql://localhost:5432/java
        username: postgres